### ISSUE TITLE
Any insight on this forbidden error, seems related to Compute Engine permissions?

### ISSUE THREAD

**Issue by oshalygin** [GoogleCloudPlatform/cloud-debug-nodejs#216]
Environment/Infrastructure: Kubernetes 1.4.7 cluster deployed on GCP.  

I'm not quite sure where to start with this, feels like all of the authentication is in place and the project is properly configured but I'm not able to get any of the logging out.  It's not even spitting out the default stuff that I see locally.

Looking at the pod that has the NodeJs application deployed, seeing lots of this:

**Failed to re-register debuggee 413636282855: Error: A Forbidden error was returned while attempting to retrieve an access token for the Compute Engine built-in service account. This may be because the Compute Engine instance does not have the correct permission scopes specified. Request had insufficient authentication scopes.**

Note that this is my configuration at the cluster level:
```yaml
resources:
- name: dev-kube
  type: container.v1.cluster
  properties:
    zone: us-central1-a
    cluster:
      description:  Web Application DEV Cluster
      nodePools:
        - name: dev-web
          initialNodeCount: 1
          autoscaling: 
            enabled: true
            minNodeCount: 1
            maxNodeCount: 5
          config:
            machineType: n1-standard-1
            diskSizeGb: 100
            serviceAccount: default
            labels:
              env: dev
      loggingService: logging.googleapis.com
      monitoringService: monitoring.googleapis.com
      network: default
      addonsConfig:
          horizontalPodAutoscaling:
            disabled: false
      network: default
```
